### ISSUE TITLE
URL  not find

### ISSUE THREAD

**Issue by Bibgithhub** [Healthcare-Robotics/spectrovision#4]
wget -O dataset/spectrovision_raw_dataset.zip https://www.dropbox.com/s/mrqmx437m7gykjg/spectrovision_raw_dataset.zip?dl=1

**Comment by Zackory** [comment]
Thanks for catching this. Here is a new link to the dataset.
```
python3 -m pip install gdown
gdown 1_PtHk2KNG_sYyFyT31hchz3R2ZO6tNwr
```

**Comment by Bibgithhub** [comment]
Thank you very much for your reply, I used the new commands you provided, but there are still some problems present, I don't know if it's just me.
        HTTPSConnectionPool(host='drive.google.com', port=443): Max retries
        exceeded with url: /uc?id=1_PtHk2KNG_sYyFyT31hchz3R2ZO6tNwr (Caused by
        NewConnectionError('<urllib3.connection.HTTPSConnection object at
        0x7fe3dfe46490>: Failed to establish a new connection: [Errno 101]
        Network is unreachable'))

**Comment by Zackory** [comment]
This looks like a known bug with gdown: https://github.com/wkentaro/gdown/issues

The command works for me on a Mac using Python 3.9.6

**Comment by Zackory** [comment]
Alternatively, you can download directly from Google Drive using this link: https://drive.google.com/file/d/1_PtHk2KNG_sYyFyT31hchz3R2ZO6tNwr/view?usp=sharing

**Comment by Bibgithhub** [comment]
> 或者，您可以使用以下链接直接从 Google Drive 下载：https://drive.google.com/file/d/1_PtHk2KNG_sYyFyT31hchz3R2ZO6tNwr/view?usp=sharing

The approach of using Google Drive to download the dataset is useful and I appreciate your reply.
